
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - controller.devfile.io
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.devfile.io
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - controller.devfile.io
  resources:
  - workspaceroutings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.devfile.io
  resources:
  - workspaceroutings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - workspace.devfile.io
  resources:
  - devworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspace.devfile.io
  resources:
  - devworkspaces/status
  verbs:
  - get
  - patch
  - update
