# permissions for end users to view workspaceroutings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspacerouting-viewer-role
rules:
- apiGroups:
  - controller.devfile.io
  resources:
  - workspaceroutings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controller.devfile.io
  resources:
  - workspaceroutings/status
  verbs:
  - get
